/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jonjts.assistant;

import br.com.jonjts.assistant.control.BackupControl;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author Jonas
 */
public class BackupTela extends JFrame {

    private Main main;
    private BackupControl backupControl;

    public Main getMain() {
        return main;
    }

    public JToggleButton getBtnBackup() {
        return btnBackup;
    }

    public JLabel getLblMyysql() {
        return lblMyysql;
    }

    public JTextField getTxtSenha() {
        return txtSenha;
    }

    public BackupTela(final Main main) {
        initComponents();
        this.main = main;
        backupControl = new BackupControl();

        main.setEnabled(false);
        txtSenha.setText("jonas");
        setResizable(false);
        setLocationRelativeTo(null);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                main.setEnabled(true);
            }
        });
    }

    private void enableAvancado(boolean anable) {
        btnMysql.setEnabled(anable);
        txtSenha.setEnabled(anable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbSimples = new javax.swing.JRadioButton();
        rbAvancado = new javax.swing.JRadioButton();
        btnBackup = new javax.swing.JToggleButton();
        txtSenha = new JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnMysql = new javax.swing.JToggleButton();
        lblMyysql = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backup");

        buttonGroup1.add(rbSimples);
        rbSimples.setSelected(true);
        rbSimples.setText("Simples");
        rbSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSimplesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAvancado);
        rbAvancado.setText("Avançado");
        rbAvancado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAvancadoActionPerformed(evt);
            }
        });

        btnBackup.setText("Fazer Backup");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        txtSenha.setToolTipText("senha do banco de dados");
        txtSenha.setEnabled(false);

        jLabel1.setText("Senha:");

        btnMysql.setText("Diretorio MySql");
        btnMysql.setEnabled(false);
        btnMysql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMysqlActionPerformed(evt);
            }
        });

        lblMyysql.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackup)
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnMysql))
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMyysql, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbAvancado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnBackup))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMysql))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbSimples)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAvancado)))
                        .addGap(18, 18, 18)
                        .addComponent(lblMyysql)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSimplesActionPerformed
        enableAvancado(false);
    }//GEN-LAST:event_rbSimplesActionPerformed

    private void rbAvancadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAvancadoActionPerformed
        enableAvancado(true);
    }//GEN-LAST:event_rbAvancadoActionPerformed

    private void btnMysqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMysqlActionPerformed
        String folder = getFolder("Selecione a pasta do MySql");
        lblMyysql.setText(folder == null ? "" : folder);
    }

    protected String getFolder(String title) throws HeadlessException {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle(title);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setVisible(true);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            return file.getPath();
        }
        return null;
    }//GEN-LAST:event_btnMysqlActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        if (rbAvancado.isSelected()) {
            doBackupVancado();
        } else {
            doBackupSimples();
        }
    }

    protected void doBackupSimples() throws HeadlessException {
        String folder = getFolder("Pasta de backup");
        if (folder != null) {
            try {
                backupControl.doBackup(backupControl.pathMysql, "jonas", folder);
                JOptionPane.showMessageDialog(null, "Backup feito em " + folder);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro\n" + ex.getMessage());
                Logger.getLogger(BackupTela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    protected void doBackupVancado() throws HeadlessException {
        if (validAvancado()) {
            String folder = getFolder("Pasta de backup");
            if (folder != null) {
                try {
                    backupControl.doBackup("\"" + lblMyysql.getText(), txtSenha.getText(), folder);
                    JOptionPane.showMessageDialog(null, "Backup feito em " + folder);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Erro\n" + ex.getMessage());
                    Logger.getLogger(BackupTela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique as informações");
        }
    }//GEN-LAST:event_btnBackupActionPerformed

    protected boolean validAvancado() {
        if (txtSenha.getText().isEmpty()) {
            return false;
        }
        if (lblMyysql.getText().trim().isEmpty()) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBackup;
    private javax.swing.JToggleButton btnMysql;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMyysql;
    private javax.swing.JRadioButton rbAvancado;
    private javax.swing.JRadioButton rbSimples;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
