/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jonjts.assistant;

import br.com.jonjts.assistant.entity.TratoGastroIntestinal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonas
 */
public class TratoGastroIntestinalTela extends javax.swing.JFrame implements ITab {

    private NovoPaciente novoPaciente;
    private TratoGastroIntestinal tratoGastroIntestinal;

    public TratoGastroIntestinalTela(NovoPaciente novoPaciente) {
        this.novoPaciente = novoPaciente;
        initComponents();
    }

    public void setTratoGastroIntestinal(TratoGastroIntestinal tratoGastroIntestinal) {
        this.tratoGastroIntestinal = tratoGastroIntestinal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbDificuldadeMastigacao = new javax.swing.JCheckBox();
        cbRefluxo = new javax.swing.JCheckBox();
        cbNauseas = new javax.swing.JCheckBox();
        cbVomitos = new javax.swing.JCheckBox();
        cbPirose = new javax.swing.JCheckBox();
        cbDisfagia = new javax.swing.JCheckBox();
        cbOdinofagia = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbApetiteAtual = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbTransitoIntestinal = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbDificuldadeMastigacao.setText("Dificuldade de mastigacao");

        cbRefluxo.setText("Refluxo");

        cbNauseas.setText("Nauseas");

        cbVomitos.setText("Vomitos");

        cbPirose.setText("Pirose");

        cbDisfagia.setText("Disfagia");

        cbOdinofagia.setText("Odinofagia");

        jLabel1.setText("Apetite atual:");

        cbApetiteAtual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preservado", "Autemtado", "Redusido" }));
        cbApetiteAtual.setSelectedIndex(-1);

        jLabel2.setText("Transito Intestinal:");

        cbTransitoIntestinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Constipação", "Diarreia", "Normal" }));
        cbTransitoIntestinal.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDificuldadeMastigacao)
                    .addComponent(cbRefluxo)
                    .addComponent(cbNauseas)
                    .addComponent(cbVomitos)
                    .addComponent(cbPirose)
                    .addComponent(cbDisfagia)
                    .addComponent(cbOdinofagia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbApetiteAtual, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTransitoIntestinal, 0, 130, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDificuldadeMastigacao)
                    .addComponent(jLabel1)
                    .addComponent(cbApetiteAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRefluxo)
                    .addComponent(jLabel2)
                    .addComponent(cbTransitoIntestinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNauseas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVomitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPirose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDisfagia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbOdinofagia)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbApetiteAtual;
    private javax.swing.JCheckBox cbDificuldadeMastigacao;
    private javax.swing.JCheckBox cbDisfagia;
    private javax.swing.JCheckBox cbNauseas;
    private javax.swing.JCheckBox cbOdinofagia;
    private javax.swing.JCheckBox cbPirose;
    private javax.swing.JCheckBox cbRefluxo;
    private javax.swing.JComboBox cbTransitoIntestinal;
    private javax.swing.JCheckBox cbVomitos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void save() {
        if (tratoGastroIntestinal == null) {
            insert();
        } else {
            update();
        }
    }

    private void insert() {
        try {
            tratoGastroIntestinal = new TratoGastroIntestinal();
            bind();
            tratoGastroIntestinal = novoPaciente.insertTratoGastroIntestinal(tratoGastroIntestinal);
            JOptionPane.showMessageDialog(null, "Trato Gastro Intestinal salvo.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar Trato Gastro Intestinal.");
            Logger.getLogger(TratoGastroIntestinalTela.class.getName()).log(Level.SEVERE, null, ex);
            tratoGastroIntestinal = null;
        }
    }

    private void update() {
        try {
            bind();
            novoPaciente.updateTratoGastroIntestinal(tratoGastroIntestinal);
            JOptionPane.showMessageDialog(null, "Trato Gastro Intestinal salvo.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar Trato Gastro Intestinal.");
            Logger.getLogger(TratoGastroIntestinalTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void bind() {
        tratoGastroIntestinal.setApetiteAtual((String) cbApetiteAtual.getSelectedItem());
        tratoGastroIntestinal.setDificuldadeMastigacao(cbDificuldadeMastigacao.isSelected());
        tratoGastroIntestinal.setDisfagia(cbDisfagia.isSelected());
        tratoGastroIntestinal.setNauseas(cbNauseas.isSelected());
        tratoGastroIntestinal.setOdinofagia(cbOdinofagia.isSelected());
        tratoGastroIntestinal.setPirose(cbPirose.isSelected());
        tratoGastroIntestinal.setRefluxo(cbPirose.isSelected());
        tratoGastroIntestinal.setTransitoIntestinal((String) cbTransitoIntestinal.getSelectedItem());
        tratoGastroIntestinal.setVomitos(cbVomitos.isSelected());
    }

    @Override
    public void clearData() {
        cbApetiteAtual.setSelectedItem(null);
        cbDificuldadeMastigacao.setSelected(false);
        cbDisfagia.setSelected(false);
        cbNauseas.setSelected(false);
        cbOdinofagia.setSelected(false);
        cbPirose.setSelected(false);
        cbRefluxo.setSelected(false);
        cbTransitoIntestinal.setSelectedItem(null);
        cbVomitos.setSelected(false);
    }

    @Override
    public void loadData() {
        cbApetiteAtual.setSelectedItem(tratoGastroIntestinal.getApetiteAtual());
        cbDificuldadeMastigacao.setSelected(tratoGastroIntestinal.getDificuldadeMastigacao());
        cbDisfagia.setSelected(tratoGastroIntestinal.getDisfagia());
        cbNauseas.setSelected(tratoGastroIntestinal.getNauseas());
        cbOdinofagia.setSelected(tratoGastroIntestinal.getOdinofagia());
        cbPirose.setSelected(tratoGastroIntestinal.getPirose());
        cbRefluxo.setSelected(tratoGastroIntestinal.getRefluxo());
        cbTransitoIntestinal.setSelectedItem(tratoGastroIntestinal.getTransitoIntestinal());
        cbVomitos.setSelected(tratoGastroIntestinal.getVomitos());
    }
}
